# Generated by Django 5.2.7 on 2026-01-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('udhar', 'Udhar (Credit)'), ('nagad', 'Nagad (Cash)'), ('udhar_vapis', 'Udhar Vapis (Repayment)')], max_length=20),
        ),
    ]
